mindmap
    )quiz app(
        (External data source)
            Updates about future paralympic games
        (Students needs)
            Browse for event information
            Search for event information
            Generate statistics
            Visualise trends and narrow the focus
            Take a quiz
            Save a quiz score
        (Teacher needs)
            Add and edit questions
            Add and edit quiz
            Add questions to quiz
            Download student scores
        (Behaviour)
            Runs in web browser
            Works on phone and PC/laptop
            Only authorised users edit data
